In [1]:
# Libraries
import pandas as pd

# Games dataset

In [2]:
games = pd.read_excel("../data/raw/games.xlsx")
games.head()

,App ID,Title,Reviews Total,Reviews Score Fancy,Release Date,Reviews D7,Reviews D30,Reviews D90,Launch Price,Tags,name_slug,Revenue Estimated,Modified Tags,Steam Page
0,730,Counter-Strike: Global Offensive,7382695,0.8800,2012-08-21,NaN,NaN,NaN,14.99,"FPS, Shooter, Multiplayer, Competitive, Action...",NaN,1.106666e+08,"FPS_, Shooter_, Multiplayer_, Competitive_, Ac...",https://store.steampowered.com/app/730
1,578080,PUBG: BATTLEGROUNDS,2201296,0.5700,2017-12-21,NaN,NaN,NaN,29.99,"Survival, Shooter, Battle Royale, Multiplayer,...",NaN,6.601687e+07,"Survival_, Shooter_, Battle Royale_, Multiplay...",https://store.steampowered.com/app/578080
2,570,Dota 2,2017009,0.8200,2013-07-09,NaN,NaN,NaN,29.99,"Free to Play, MOBA, Multiplayer, Strategy, eSp...",NaN,6.049010e+07,"Free to Play_, MOBA_, Multiplayer_, Strategy_,...",https://store.steampowered.com/app/570
3,271590,Grand Theft Auto V,1322782,0.8985,2015-04-13,NaN,NaN,NaN,29.99,"Open World, Action, Multiplayer, Crime, Automo...",NaN,3.967023e+07,"Open World_, Action_, Multiplayer_, Crime_, Au...",https://store.steampowered.com/app/271590
4,359550,Tom Clancy's Rainbow Six® Siege,978762,0.8600,2015-12-01,NaN,NaN,NaN,59.99,"FPS, PvP, eSports, Shooter, Multiplayer, Tacti...",NaN,5.871593e+07,"FPS_, PvP_, eSports_, Shooter_, Multiplayer_, ...",https://store.steampowered.com/app/359550

In [3]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 65111 entries, 0 to 65110
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   App ID               65111 non-null  int64
 1   Title                65111 non-null  object
 2   Reviews Total        65111 non-null  int64
 3   Reviews Score Fancy  65111 non-null  float64
 4   Release Date         65111 non-null  datetime64[us]
 5   Reviews D7           0 non-null      float64
 6   Reviews D30          0 non-null      float64
 7   Reviews D90          0 non-null      float64
 8   Launch Price         65111 non-null  float64
 9   Tags                 65111 non-null  str
 10  name_slug            0 non-null      float64
 11  Revenue Estimated    65111 non-null  float64
 12  Modified Tags        65111 non-null  str
 13  Steam Page           65111 non-null  str
dtypes: datetime64[us](1), float64(7), int64(2), object(1), str(3)
memory usage: 7.0+ MB

In [4]:
print(len(games) - games["App ID"].nunique())

2

In [5]:
duplicate_games = games[games["App ID"].duplicated(keep=False)]
duplicate_games

# Seems to be an error in the launch price. Remove the unplausable prices.

,App ID,Title,Reviews Total,Reviews Score Fancy,Release Date,Reviews D7,Reviews D30,Reviews D90,Launch Price,Tags,name_slug,Revenue Estimated,Modified Tags,Steam Page
17043,884990,Absinth,69,0.69,2020-10-23,NaN,NaN,NaN,13.00,"Indie, Puzzle, Horror, Psychological Horror, A...",NaN,897.00,"Indie_, Puzzle_, Horror_, Psychological Horror...",https://store.steampowered.com/app/884990
17070,884990,Absinth,69,0.69,2020-10-23,NaN,NaN,NaN,175.00,"Indie, Puzzle, Horror, Psychological Horror, A...",NaN,12075.00,"Indie_, Puzzle_, Horror_, Psychological Horror...",https://store.steampowered.com/app/884990
22767,1462790,Fight of Animals: Arena,35,0.91,2020-12-17,NaN,NaN,NaN,12.99,"Memes, PvP, 4 Player Local, Multiplayer, Local...",NaN,454.65,"Memes_, PvP_, 4 Player Local_, Multiplayer_, L...",https://store.steampowered.com/app/1462790
22839,1462790,Fight of Animals: Arena,35,0.91,2020-12-17,NaN,NaN,NaN,299.00,"Memes, PvP, 4 Player Local, Multiplayer, Local...",NaN,10465.00,"Memes_, PvP_, 4 Player Local_, Multiplayer_, L...",https://store.steampowered.com/app/1462790

In [6]:
games.drop(index=[17070, 22839], inplace=True)

In [7]:
print(len(games) - games["App ID"].nunique())

0

In [8]:
# Remove null columns
games.drop(columns=["name_slug","Reviews D7", "Reviews D30", "Reviews D90"], inplace=True)

In [9]:
games.head()

,App ID,Title,Reviews Total,Reviews Score Fancy,Release Date,Launch Price,Tags,Revenue Estimated,Modified Tags,Steam Page
0,730,Counter-Strike: Global Offensive,7382695,0.8800,2012-08-21,14.99,"FPS, Shooter, Multiplayer, Competitive, Action...",1.106666e+08,"FPS_, Shooter_, Multiplayer_, Competitive_, Ac...",https://store.steampowered.com/app/730
1,578080,PUBG: BATTLEGROUNDS,2201296,0.5700,2017-12-21,29.99,"Survival, Shooter, Battle Royale, Multiplayer,...",6.601687e+07,"Survival_, Shooter_, Battle Royale_, Multiplay...",https://store.steampowered.com/app/578080
2,570,Dota 2,2017009,0.8200,2013-07-09,29.99,"Free to Play, MOBA, Multiplayer, Strategy, eSp...",6.049010e+07,"Free to Play_, MOBA_, Multiplayer_, Strategy_,...",https://store.steampowered.com/app/570
3,271590,Grand Theft Auto V,1322782,0.8985,2015-04-13,29.99,"Open World, Action, Multiplayer, Crime, Automo...",3.967023e+07,"Open World_, Action_, Multiplayer_, Crime_, Au...",https://store.steampowered.com/app/271590
4,359550,Tom Clancy's Rainbow Six® Siege,978762,0.8600,2015-12-01,59.99,"FPS, PvP, eSports, Shooter, Multiplayer, Tacti...",5.871593e+07,"FPS_, PvP_, eSports_, Shooter_, Multiplayer_, ...",https://store.steampowered.com/app/359550

# Player Dataset

In [10]:
profile = pd.read_csv("../data/raw/profile.csv")
profile.head()

   hours_on_record  hours_last_2_weeks   appid  profile_code
0         0.466667                 0.0  218620       1393209
1         7.916667                 0.0  266840       1393209
2         7.916667                 0.0  266840       1393209
3       163.816667                 0.0  271590       1393209
4       163.816667                 0.0  271590       1393209

In [11]:
profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 148661772 entries, 0 to 148661771
Data columns (total 4 columns):
 #   Column              Dtype
---  ------              -----
 0   hours_on_record     float64
 1   hours_last_2_weeks  float64
 2   appid               int64
 3   profile_code        int64
dtypes: float64(2), int64(2)
memory usage: 4.4 GB

In [12]:
# Check null values as too large for .info() to show
print(profile.isna().sum())

hours_on_record       0
hours_last_2_weeks    0
appid                 0
profile_code          0
dtype: int64

In [13]:
duplicate_profile = profile[profile.duplicated()]
duplicate_profile

           hours_on_record  hours_last_2_weeks   appid  profile_code
2                 7.916667                 0.0  266840       1393209
4               163.816667                 0.0  271590       1393209
6                 9.350000                 0.0  304930       1393209
9                 3.100000                 0.0  346110       1393209
10                3.100000                 0.0  346110       1393209
...                    ...                 ...     ...           ...
148661759         0.800000                 0.0  304930       9542147
148661761         0.600000                 0.0  382110       9542147
148661762         0.600000                 0.0  382110       9542147
148661765         0.400000                 0.0  291480       9542147
148661771         1.900000                 0.0  433850       9542147

[62071082 rows x 4 columns]

In [14]:
profile.drop_duplicates(inplace=True)

In [15]:
print(profile.duplicated(subset=["profile_code", "appid"]).sum())

0

# Steam Dataset

In [30]:
steam = pd.read_csv("../data/raw/steam.csv")
steam.head()

,month,avg_players,gain,gain_percent,peak_players,name,steam_appid
0,Sep-25,7805.25,883.12,0.1276,13254,Counter-Strike,10
1,Aug-25,6922.13,-449.35,-0.0610,12168,Counter-Strike,10
2,Jul-25,7371.48,-833.5,-0.1016,13951,Counter-Strike,10
3,Jun-25,8204.98,-847.53,-0.0936,15798,Counter-Strike,10
4,May-25,9052.51,-471.31,-0.0495,15333,Counter-Strike,10

In [31]:
steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 612265 entries, 0 to 612264
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   month         612265 non-null  str
 1   avg_players   612265 non-null  float64
 2   gain          612265 non-null  str
 3   gain_percent  612265 non-null  float64
 4   peak_players  612265 non-null  int64
 5   name          612265 non-null  str
 6   steam_appid   612265 non-null  int64
dtypes: float64(2), int64(2), str(3)
memory usage: 32.7 MB

In [32]:
duplicate_steam = steam[steam.duplicated()]
duplicate_steam

Empty DataFrame
Columns: [month, avg_players, gain, gain_percent, peak_players, name, steam_appid]
Index: []

In [33]:
print(steam.duplicated(subset=["steam_appid", "month"]).sum())

0

In [34]:
steam['month'] = pd.to_datetime(steam['month'], format="%b-%y")
steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 612265 entries, 0 to 612264
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   month         612265 non-null  datetime64[us]
 1   avg_players   612265 non-null  float64
 2   gain          612265 non-null  str
 3   gain_percent  612265 non-null  float64
 4   peak_players  612265 non-null  int64
 5   name          612265 non-null  str
 6   steam_appid   612265 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 32.7 MB

In [35]:
steam["gain"] = pd.to_numeric(steam["gain"], errors="coerce")
steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 612265 entries, 0 to 612264
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   month         612265 non-null  datetime64[us]
 1   avg_players   612265 non-null  float64
 2   gain          605537 non-null  float64
 3   gain_percent  612265 non-null  float64
 4   peak_players  612265 non-null  int64
 5   name          612265 non-null  str
 6   steam_appid   612265 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(2), str(1)
memory usage: 32.7 MB

In [ ]:
games.to_csv("../data/processed/games_clean.csv", index=False, encoding="utf-8")

profile.to_csv("../data/processed/profile_clean.csv", index=False, encoding="utf-8")

steam.to_csv("../data/processed/steam_clean.csv", index=False, encoding="utf-8")